bitch/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

dice/urls.py
from django.conf.urls import url

from . import views

app_name = 'dice'
urlpatterns = [
    url(r'^$', views.index, name='index')
]

front/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

landing/urls.py
from django.conf.urls import url

from . import views

app_name = 'landing'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^(?P<app_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^resources/$', views.resources, name='resources')
]

raspberry/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('landing.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^bitch/', include('bitch.urls')),
    url(r'^dice/', include('dice.urls')),
    url(r'^landing/', include('landing.urls'))
]

bitch/models.py
from django.db import models

# Create your models here.

dice/models.py
from django.db import models

# Create your models here.

class Zone(models.Model):
	name=models.CharField(max_length=200)
	red=models.IntegerField()
	blue=models.IntegerField()
	black=models.IntegerField()
	yellow=models.IntegerField()
	def __str__(self):
		return self.name

	class Meta:
		abstract=True


class Continent(Zone):
	num=models.PositiveIntegerField(primary_key=True)

class Game(models.Model):
	EASY = 0
	NORMAL = 5
	HARD = 10
	DIFFICULTIES= (
		(EASY, 'Easy'),
		(NORMAL, 'Normal'),
		(HARD, 'Hard')
	)

	outbreaks=models.PositiveIntegerField(default=0)
	epidemicCount=models.PositiveIntegerField(default=NORMAL)

class Player(models.Model):
	name=models.CharField(max_length=200)
	role=models.CharField(max_length=50)
	def __str__(self):
		return self.name

landing/models.py
from django.db import models

# Create your models here.
class App(models.Model):
	title = models.CharField(max_length=200)
	latest_version = models.IntegerField()
	synopsis = models.TextField(blank=True, null=True)
	start_date = models.DateTimeField('date initiated')
	last_update = models.DateTimeField('date updated')
	page = models.CharField(max_length=200, blank=True, null=True)
	def __str__(self):
		return self.title

class Post(models.Model):
    title_text = models.CharField(max_length=200)
    body_text = models.TextField(blank=True, null=True)
    post_date = models.DateTimeField('date created')
    def __str__(self):
        return self.title_text

class Comment(models.Model):
    title_text = models.CharField(max_length=200)
    body_text = models.TextField(blank=True, null=True)
    post_date = models.DateTimeField('date updated')
    def __str__(self):
        return self.title_text

bitch/views.py
from django.shortcuts import render
from twilio import twiml
from django_twilio.decorators import twilio_view

# Create your views here.
from django.http import HttpResponse


def index(request):
    return HttpResponse("The bitch is rebuilding, be patient...")

@twilio_view
def reply_to_sms_messages(request):
    r = twiml.Response()
    r.message('Thanks for the SMS message!')
    return r

dice/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.core import serializers
from .models import Continent
# Create your views here.
def index(request):
	json_data = serializers.serialize("json",Continent.objects.all())
	context = {
	"json": json_data,
	}
	return render(request, 'dice/index.html', context)

landing/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader

from .models import App, Post

# Create your views here.
def index(request):
	posts = Post.objects.all()
	context = {'posts': posts}
	return render(request, 'landing/index.html')

def list(request):
	apps = App.objects.all()
	context = {'apps': apps}
	return render(request, 'landing/list.html', context)

def detail(request, app_id):
	app = get_object_or_404(App, pk=app_id)
	context = {'app_id': app_id, 'app': app}
	return render(request, 'landing/detail.html', context)

def resources(request):
	return HttpResponse("This is where I give credit where credit is due!")

dice/templates/dice/index.html
 {% load staticfiles %}
 {% block css %}
<link rel="stylesheet" href="{% static 'dice/dice.css' %}" />
 {% endblock %}

 {% block js %}
<script src="{% static 'dice/knockout-3.4.0.js' %}"></script>
<script src="{% static 'dice/jquery.min.js' %}"></script>
<script src="{% static 'dice/dice.js' %}"></script>
{% endblock %}

 <h1>Welcome to DICE</h1>
  <a href='{% url 'landing:index' %}'>Take Me Home</a>
  <p></p>
  <button id="start">New Game</button>
  <p></p>
  <table id="counters"></table>
  <p></p>
  <table id="continents"></table>
  <p></p>
  <table id="treatmentCenter"></table>
  <p></p>
  <table id="cdc"></table>
  <p></p>
  <table id="currentRoll"></table>
  <p></p>
  <table id="players"></table>
  <!-- Not Yet Implemented
<div id="charpick" hidden>
    <form class="charpick">
        <label for="numPlayers">Number of Players (2-5):</label>
        <input type="text" name="numPlayers" id="numPlayers" value="2"><br>
        Assignment Style:
        <input type="radio" name="selectPref" id="random" value="random" checked><label for="random">Random</label><br>
        <input type="radio" name="selectPref" id="pickTwo" value="pickTwo"><label for="pickTwo">Pick from Two</label><br>
        <input type="radio" name="selectPref" id="pickAny" value="pickAny"><label for="pickAny">Pick from All</label><br>
        <input type="submit" value="submit" id="submitSelectionPref">
    </form>
</div>
<div id="charselect" hidden>
</div>
-->

landing/templates/landing/detail.html
<h1>Thing {{ app_id }}</h1>
<ul>
	<li>{{ app.title }}</li>
	<li>Created {{ app.start_date }}</li>
	<li>Last Updated: {{ app.last_update }}</li>
	<li>{{ app.synopsis }}</li>
	<li><a href="{% url app.page %}">GO!</a></li>
</ul>

landing/templates/landing/dice.html
 {% load staticfiles %}
 {% block css %}
<link rel="stylesheet" href="{% static 'landing/dice.css'%}" />
 {% endblock %}

 {% block js %}
<script src="{% static 'landing/jquery.min.js'%}"></script>
<script src="{% static 'landing/dice.js'%}"></script>
{% endblock %}

 <h1>Welcome to DICE</h1>
  <button id="start">New Game</button>
  <p></p>
  <table id="counters"></table>
  <p></p>
  <table id="continents"></table>
  <p></p>
  <table id="treatmentCenter"></table>
  <p></p>
  <table id="cdc"></table>
  <p></p>
  <table id="currentRoll"></table>
  <p></p>
  <table id="players"></table>
  <!-- Not Yet Implemented
<div id="charpick" hidden>
    <form class="charpick">
        <label for="numPlayers">Number of Players (2-5):</label>
        <input type="text" name="numPlayers" id="numPlayers" value="2"><br>
        Assignment Style:
        <input type="radio" name="selectPref" id="random" value="random" checked><label for="random">Random</label><br>
        <input type="radio" name="selectPref" id="pickTwo" value="pickTwo"><label for="pickTwo">Pick from Two</label><br>
        <input type="radio" name="selectPref" id="pickAny" value="pickAny"><label for="pickAny">Pick from All</label><br>
        <input type="submit" value="submit" id="submitSelectionPref">
    </form>
</div>
<div id="charselect" hidden>
</div>
-->

landing/templates/landing/index.html
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'landing/style.css'%}" />
 {% endblock %}
<div id="header">
<h1>Gloriously DECIDUOUSLY</h1>
<p></p>
<div id="posts">
{% if posts %}
	<ul>
		{% for post in posts %}
			<b>{{ post.title_text }}</b>
			{{ post.body_text }}
		{% endfor %}
	</ul>
{% else %}
	<p><strong>Under Construction...bzurrrt hiss ploink</strong></p>
{% endif %}
<p></p>
<a href="{% url 'dice:index' %}">Dice Game</a>
</div></div>

landing/templates/landing/list.html
These are all the things I have:

{% if apps %}
	<ul>
		{% for app in apps %}
			<li><a href="{% url 'landing:detail' app.id %}">{{ app.title }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No apps in Apps!</p>
{% endif %}